OnlineShop/Controllers/HomeController.cs
using Model.DAO;
using Model.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineShop.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            ViewBag.slides = new SlideDAO().ListAll();
            ViewBag.newproduct = new ProductDAO().ListNewUpdateProduct(5);
            ViewBag.popularpro = new ProductDAO().ListPopularProduct(5);
            ViewBag.newscon = new ContentDAO().ListAllContent();

            var DAOmenu = new MenuDAO();
            var DAOprocate = new ProductCategoryDAO();
            List<Menu> listMenu = DAOmenu.ListAll();
            listMenu.RemoveAt(DAOmenu.ListAll().Count - 1);
            List<object> myModel = new List<object>();
            myModel.Add(listMenu);
            myModel.Add(DAOprocate.ListAll());
            return View(myModel);
        }

        [ChildActionOnly]
        public ActionResult _Menu()
        {
            var DAOmenu = new MenuDAO();
            var DAOprocate = new ProductCategoryDAO();
            List<object> myModel = new List<object>();
            myModel.Add(DAOmenu.ListAll());
            myModel.Add(DAOprocate.ListAll());
            return PartialView(myModel);
        }



        public PartialViewResult ProductWithItem(long? idcatei)
        {
            var DAOproduct = new ProductDAO();
            List<Product> listPro = new List<Product>();
            listPro = DAOproduct.ListProduct(10, idcatei);
            return PartialView(listPro);
        }


    }
}

OnlineShop/Controllers/NewsController.cs
using Model.DAO;
using Model.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineShop.Controllers
{
    public class NewsController : Controller
    {
        // GET: News
        public ActionResult Index()
        {
            CategoryDAO category = new CategoryDAO();
            ContentDAO content = new ContentDAO();
            List<object> listob = new List<object>();
            listob.Add(category.ListAllCategory());
            listob.Add(content.ListAllContent());

            return View(listob);
        }

        public PartialViewResult ListCNews(long idconn)
        {
            ContentDAO content = new ContentDAO();
            List<Content> listCon = content.ListConCategory(idconn);
            return PartialView(listCon);
        }


        public ActionResult DetailNewsContent(long iddetailconn)
        {
            ContentDAO content = new ContentDAO();
            Content cont = content.ViewDetail((int)iddetailconn);
            return View(cont);
        }


    }
}

OnlineShop/Controllers/ProductController.cs
using Model.DAO;
using Model.EntityFramework;
using OnlineShop.Common;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace OnlineShop.Controllers
{
    public class ProductController : Controller
    {
        // GET: Product
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult CategoryPro(long idcatepro, int page = 1, int pageSize = 3)
        {
            ViewBag.Category = new ProductCategoryDAO().ViewDetail((int)idcatepro);

            int totalRecord = 0;
            var model = new ProductDAO().ListByCategoryId(idcatepro, ref totalRecord, page, pageSize);
            ViewBag.Total = totalRecord;
            ViewBag.Page = page;
            int maxPage = 5;
            int totalPage = 0;
            totalPage = (int)Math.Ceiling((double)(totalRecord / pageSize));
            ViewBag.TotalPage = totalPage;
            ViewBag.MaxPage = maxPage;
            ViewBag.First = 1;
            ViewBag.Last = totalPage;
            ViewBag.Next = page + 1;
            ViewBag.Prev = page - 1;

            return View(model);
        }





        public ActionResult ProductDetails(long? idpro)
        {
            ViewBag.newproduct = new ProductDAO().ListNewUpdateProduct(5);
            var product = new ProductDAO().ViewDetail((int)idpro.Value);
            if (product.MoreImages != null)
            {
                string[] img = product.MoreImages.Split(',');
                List<string> listimg = new List<string>();
                for (int i = 0; i < img.Length; i++)
                {
                    if (img[i] != string.Empty)
                    {
                        listimg.Add(img[i]);
                    }
                }
                ViewBag.listimage = listimg;
            }
            return View(product);
        }


        public PartialViewResult _ProductCategory(long? idcateit)
        {
            var DAOproduct = new ProductDAO();
            List<Product> listPro = new List<Product>();
            listPro = DAOproduct.ListProductFirstRun(10, idcateit);
            return PartialView(listPro);
        }



        [ChildActionOnly]
        public ActionResult _Ads(long? idc)
        {
            var DAOAds = new AdDAO();
            List<Ad> listAds = DAOAds.ListAll();
            List<Ad> listAd = new List<Ad>();
            if (idc != 0 && idc != 1)
            {
                Ad ad = new Ad();
                ad.Image = listAds[(int)((int)idc - 2)].Image;

                listAd.Add(ad);
            }
            return PartialView(listAd);
        }


        public JsonResult ListProductWithItem(string product)
        {
            product = product.Replace(".", " ").Replace("₫", " ").Replace(" ", "");

            var jsonProduct = new JavaScriptSerializer().Deserialize<List<Product>>(product);
            foreach (var item in jsonProduct)
            {
                item.Images = "/Data/images/636310466030005418_s81o.jpg";
                item.Name = "Samsung-Galaxy-S8";
            }
            ViewBag.datac = jsonProduct;

            return Json(new { status = true });
        }


    }
}

OnlineShop/Controllers/SearchController.cs
using Model.DAO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineShop.Controllers
{
    public class SearchController : Controller
    {
        // GET: Search
        public ActionResult Index()
        {
            return View();
        }


        public PartialViewResult SearchListPro(string keyword, string dropKey, int page = 1, int pageSize = 18)
        {
            //ViewBag.Category = new ProductCategoryDAO().ViewDetail((int)idcatepro);

            int totalRecord = 0;
            var model = new ProductDAO().ListAllSearch(keyword, dropKey, ref totalRecord, page, pageSize);

            ViewBag.Total = totalRecord;
            ViewBag.Page = page;
            int maxPage = 5;
            int totalPage = 0;
            totalPage = (int)Math.Ceiling((double)(totalRecord / pageSize));
            ViewBag.TotalPage = totalPage;
            ViewBag.MaxPage = maxPage;
            ViewBag.First = 1;
            ViewBag.Last = totalPage;
            ViewBag.Next = page + 1;
            ViewBag.Prev = page - 1;
            return PartialView(model);
        }
        

        public ActionResult _Search()
        {
            return PartialView();
        }
    }
}

OnlineShop/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var slides = (List<Model.EntityFramework.Slide>)ViewBag.slides;
    var listnewpro = (List<Model.EntityFramework.Product>)ViewBag.newproduct;
    var popularpro  = (List<Model.EntityFramework.Product>)ViewBag.popularpro;

    var listContent = (List<Model.EntityFramework.Content>)ViewBag.newscon;

}
@model IEnumerable<object>
@{
    List<Model.EntityFramework.Menu> listMenu = Model.ToList()[0] as List<Model.EntityFramework.Menu>;
    List<Model.EntityFramework.ProductCategory> listProCate = Model.ToList()[1] as List<Model.EntityFramework.ProductCategory>;
}
@section jsCus{
    <script>
        $('#btnSearchkey').click(function() {
            $('.contentHome').removeClass("show").addClass("hide");
        })
    </script>
<link href="/Assets/Client/css/listpro.css" rel="stylesheet" />
<link href="/Assets/Client/css/news.css" rel="stylesheet" />
  
}
<div class="row" id="searchResult">
@Html.Action("SearchListPro", "Search", new { keyword = "", dropKey = "" })
</div>

<div class="row show contentHome" id="contentLarge">
    
    <div class="col-sm-3">
        <div class="itempopular">Bán Chạy</div>
        <div class="ipopular">
            @foreach (var item in popularpro)
            {
                <span>
                    <img src="@item.Images" />
                    <a href="san-pham-con/@item.MetaTitle-@item.ID"><p>@item.Name</p></a>
                    <p>@string.Format("{0:C}", item.Price).Replace(",00", "")</p>
                </span>
            }
        </div>
        <div class="itempopular">Mới Cập Nhật</div>
        <div class="ipopular">
            @foreach (var item in listnewpro)
            {
                <span>
                    <img src="@item.Images" />
                    <a href="san-pham-con/@item.MetaTitle-@item.ID"><p>@item.Name</p></a>
                    <p>@string.Format("{0:C}", item.Price).Replace(",00", "")</p>
                </span>
            }

        </div>

        <!--News-->
        <div class="newsupitem">Tin mới</div>
        <div class="inewsup">
            @foreach (var item in listContent)
            {
                <div>
                    <img src="@item.Images" width="60" height="60" />
                    <a href="@Url.Action("DetailNewsContent","News",new {@iddetailconn=item.ID})"><p>@item.Name</p></a>

                    <span class="glyphicon glyphicon-calendar">@item.CreatedDate.Value.ToString("dd/MM/yyyy")</span>
                </div>
            }

        </div>

    </div>
    <div class="col-sm-9">
        <div id="slidemain">
            <ul class="rslides">
                @foreach (var item in slides)
                {
                    <li>
                        <embed src="@item.Image" alt="@item.Description">
                    </li>
                }
            </ul>
        </div>

        <!--Product-->
        @{ var i = 0;}
        @foreach (var item in listMenu)
        {

            <div class="categoryLarge">
                <ul>
                    @foreach (var itemc in listProCate)
                    {
                        if (item.ID == itemc.ParentID)
                        {
                            <li><a href="#" id="btnProCate" data-id="@itemc.ID">@Ajax.ActionLink(itemc.Name, "ProductWithItem", "Home", new { @idcatei = itemc.ID }, new AjaxOptions()
                                                                          {
                                                                              UpdateTargetId = "productSlide_"+item.ID,
                                                                              InsertionMode = InsertionMode.Replace

                                                                          }) </a></li>
                        }
                    }
                </ul>
            </div>

             <!--Item Product-->
            <div class="slider1 proSlide_@item.ID" id="productSlide_@item.ID">
                @{ Html.RenderAction("_ProductCategory", "Product", new { idcateit = item.ID }); }

            </div>
            
            i++;

            { Html.RenderAction("_Ads", "Product", new { idc = i }); }
        }

    </div>
</div>

OnlineShop/Views/Home/ProductWithItem.cshtml
@model List<Model.EntityFramework.Product>
@using Model.EntityFramework;
@section jsCus{


    }

<!--Item Product-->
@if (Model != null)
{
    foreach (var item in Model)
    {
        <div class="slide" data-id="@item.CategoryID">
            <div>
                <img src="@item.Images" />
            </div>
            <a href="san-pham-con/@item.MetaTitle-@item.ID"><h4>@item.Name</h4></a>
            <h5>@string.Format("{0:C}", item.Price).Replace(",00", "")</h5>

            <a href="@Url.Action("AddProToCart", "Cart",new { idtocart = item.ID,quantity=1})" title="Thêm vào giỏ">
                <svg style="width:24px;height:24px" viewBox="0 0 24 24">
                    <path fill="#282B3A"
                          d="M17,18A2,2 0 0,1 19,20A2,2 0 0,1 17,22C15.89,22 15,21.1 15,20C15,18.89 15.89,18 17,18M1,2H4.27L5.21,4H20A1,1 0 0,1 21,5C21,5.17 20.95,5.34 20.88,5.5L17.3,11.97C16.96,12.58 16.3,13 15.55,13H8.1L7.2,14.63L7.17,14.75A0.25,0.25 0 0,0 7.42,15H19V17H7C5.89,17 5,16.1 5,15C5,14.65 5.09,14.32 5.24,14.04L6.6,11.59L3,4H1V2M7,18A2,2 0 0,1 9,20A2,2 0 0,1 7,22C5.89,22 5,21.1 5,20C5,18.89 5.89,18 7,18M16,11L18.78,6H6.14L8.5,11H16Z" />
                </svg>
            </a>

        </div>
    }
}