OnlineShop/Areas/Admin/Controllers/ProductController.cs
using Model.DAO;
using Model.EntityFramework;
using OnlineShop.Common;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineShop.Areas.Admin.Controllers
{
    public class ProductController : BaseController
    {
        // GET: Admin/Product
        public ActionResult Index(string searchString, int page = 1, int pageSize = 6)
        {
            var DAO = new ProductDAO();
            var model = DAO.ListAllProduct(searchString, page, pageSize);
            ViewBag.SearchString = searchString;
            return View(model);
        }
        [HttpGet]
        public ActionResult Create()
        {
            SetViewBag();
            return View();
        }

        public ActionResult Edit(int id)
        {
            var product = new ProductDAO().ViewDetail(id);
            SetViewBag(product.CategoryID);
            return View(product);
        }

        [HttpPost]
        [ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Product product)
        {
            if (ModelState.IsValid)
            {
                var DAO = new ProductDAO();
                product.MetaTitle = ConvertToUnSign.convertunsign(product.MetaTitle);
                long id = DAO.Insert(product);
                if (id > 0)
                {
                    SetAlert("Thêm thành công", "success");
                    return RedirectToAction("Index", "Product");
                }
                else
                {
                    SetAlert("Thêm thất bại", "error");
                    ModelState.AddModelError("", "Thêm thất bại");
                }
            }
            SetViewBag();
            return View("Index");
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(Product product)
        {
            if (ModelState.IsValid)
            {
                var DAO = new ProductDAO();
                product.MetaTitle = ConvertToUnSign.convertunsign(product.MetaTitle);
                var result = DAO.Update(product);
                if (result)
                {
                    SetAlert("Cập nhật thành công", "success");
                    return RedirectToAction("Index", "Product");
                }
                else
                {
                    SetAlert("Cập nhật thất bại", "error");
                    ModelState.AddModelError("", "Cập nhật thất bại");
                }
            }
            SetViewBag(product.CategoryID);
            return View("Index");
        }

        [HttpDelete]
        public ActionResult Delete(int id)
        {
            new ProductDAO().Delete(id);
            SetAlert("Xóa thành công", "success");
            return RedirectToAction("Index", "Product");
        }


        [HttpPost]
        public JsonResult ChangeStatus(long id)
        {
            var result = new ProductDAO().ChangeStatus(id);
            return Json(new
            {
                status = result
            });
        }


        public void SetViewBag(long? selectedId = null)
        {
            var DAO = new ProductCategoryDAO();
            ViewBag.ProductCategoryID = new SelectList(DAO.ListAll(), "ID", "Name", selectedId);
        }
        

    }
}

OnlineShop/Controllers/DetailProductController.cs
using Model.DAO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineShop.Controllers
{
    public class DetailProductController : Controller
    {
        // GET: DetailProduct
        public ActionResult Index()
        {
            return View();
        }


        [ChildActionOnly]
        public ActionResult _ConfigDesAjax(long idconfig)
        {
            var product = new ProductDAO().ViewDetail((int)idconfig);


            return PartialView(product);
        }

        [ChildActionOnly]
        public ActionResult _DesDetailAjax(long iddes)
        {
            var product = new ProductDAO().ViewDetail((int)iddes);

            return PartialView(product);
        }






    }
}

OnlineShop/Controllers/ProductController.cs
using Model.DAO;
using Model.EntityFramework;
using OnlineShop.Common;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace OnlineShop.Controllers
{
    public class ProductController : Controller
    {
        // GET: Product
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult CategoryPro(long idcatepro, int page = 1, int pageSize = 3)
        {
            ViewBag.Category = new ProductCategoryDAO().ViewDetail((int)idcatepro);

            int totalRecord = 0;
            var model = new ProductDAO().ListByCategoryId(idcatepro, ref totalRecord, page, pageSize);
            ViewBag.Total = totalRecord;
            ViewBag.Page = page;
            int maxPage = 5;
            int totalPage = 0;
            totalPage = (int)Math.Ceiling((double)(totalRecord / pageSize));
            ViewBag.TotalPage = totalPage;
            ViewBag.MaxPage = maxPage;
            ViewBag.First = 1;
            ViewBag.Last = totalPage;
            ViewBag.Next = page + 1;
            ViewBag.Prev = page - 1;

            return View(model);
        }





        public ActionResult ProductDetails(long? idpro)
        {
            ViewBag.newproduct = new ProductDAO().ListNewUpdateProduct(5);
            var product = new ProductDAO().ViewDetail((int)idpro.Value);
            if (product.MoreImages != null)
            {
                string[] img = product.MoreImages.Split(',');
                List<string> listimg = new List<string>();
                for (int i = 0; i < img.Length; i++)
                {
                    if (img[i] != string.Empty)
                    {
                        listimg.Add(img[i]);
                    }
                }
                ViewBag.listimage = listimg;
            }
            return View(product);
        }


        public PartialViewResult _ProductCategory(long? idcateit)
        {
            var DAOproduct = new ProductDAO();
            List<Product> listPro = new List<Product>();
            listPro = DAOproduct.ListProductFirstRun(10, idcateit);
            return PartialView(listPro);
        }



        [ChildActionOnly]
        public ActionResult _Ads(long? idc)
        {
            var DAOAds = new AdDAO();
            List<Ad> listAds = DAOAds.ListAll();
            List<Ad> listAd = new List<Ad>();
            if (idc != 0 && idc != 1)
            {
                Ad ad = new Ad();
                ad.Image = listAds[(int)((int)idc - 2)].Image;

                listAd.Add(ad);
            }
            return PartialView(listAd);
        }


        public JsonResult ListProductWithItem(string product)
        {
            product = product.Replace(".", " ").Replace("₫", " ").Replace(" ", "");

            var jsonProduct = new JavaScriptSerializer().Deserialize<List<Product>>(product);
            foreach (var item in jsonProduct)
            {
                item.Images = "/Data/images/636310466030005418_s81o.jpg";
                item.Name = "Samsung-Galaxy-S8";
            }
            ViewBag.datac = jsonProduct;

            return Json(new { status = true });
        }


    }
}

OnlineShop/Views/Product/CategoryPro.cshtml
@model List<Model.EntityFramework.Product>

@{
    ViewBag.Title = "CategoryPro";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var category = (Model.EntityFramework.ProductCategory)ViewBag.Category;
}
@section jsCus{
    <link href="/Assets/Client/css/listpro.css" rel="stylesheet" />
}
<div class="row" id="contentLarge">
    <div class="col-sm-10 col-sm-offset-1" id="listProLarge">
        <section id="deals">
            @foreach (var item in Model)
            {
                <section class="sale-item ">
                    <img src="@item.Images"
                         alt="@item.Name" />
                    <a href="@Url.Action("ProductDetails","Product",new {idpro=@item.ID })">@item.Name</a>
                    <p>@string.Format("{0:C}", item.Price).Replace(",00", "")</p>
                    <a href="@Url.Action("AddProToCart", "Cart",new { idtocart = item.ID,quantity=1})" title="Thêm vào giỏ">
                        <span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span>
                    </a>
                </section>
            }

        </section>
    </div>
</div>
<!--Page-->
<div class="row">
    <div class="col-sm-6 col-sm-offset-3">
        @if (ViewBag.TotalPage > 1)
        {
            var pageDisplay = (int)ViewBag.MaxPage;
            int totalPage = (int)ViewBag.TotalPage;
            int currentPage = ((int)ViewBag.Page);
            var startPageIndex = Math.Max(1, currentPage - pageDisplay / 2);
            var endPageIndex = Math.Min(totalPage, currentPage + pageDisplay / 2);
            string[] listlink = Request.Url.AbsoluteUri.ToString().Split('&');
            var link = listlink[0];
            <nav aria-label="Page navigation" style="text-align:center">
                <ul class="pagination">
                    @if (currentPage > ViewBag.First)
                {
                        <li>
                            <a href="@link&page=@ViewBag.First" title="Trang đầu" class="first disabled">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                            <a href="@link&page=@ViewBag.Prev" title="Trang trước" class="prev disabled">
                                <i class="fa fa-angle-left"></i>
                            </a>
                        </li>
                    }
                    @for (int i = startPageIndex; i <= endPageIndex; i++)
                    {
                        if (currentPage == i)
                        {
                            <li><a href="@link&page=@i" title="Trang @i" class="active">@i <span class="sr-only">(current)</span></a></li>
                        }
                        else
                        {
                            <li><a href="@link&page=@i" title="Trang @i" class="disabled">@i</a></li>
                        }

                    }
                    @if (currentPage < totalPage)
                    {
                        <li>
                            <a href="@link&page=@ViewBag.Next" title="Trang sau" class="next disabled">
                                <i class="fa fa-angle-right"></i>
                            </a>
                            <a href="@link&page=@ViewBag.Last" title="Trang cuối" class="last disabled">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        </li>
                    }
                </ul>
            </nav>


        }

    </div>
</div>

OnlineShop/Views/Product/ProductDetails.cshtml
@model Model.EntityFramework.Product
@{
    ViewBag.Title = "ProductDetails";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var listnewpro = (List<Model.EntityFramework.Product>)ViewBag.newproduct;
}
@section jsCus{
    <script src="/Assets/Client/js/adminajax.js"></script>
    <script>
        $(document).ready(function () {
            $('#addtothecart').click(function () {
                var quantitydata = $('#datanumbercart').val();
                var id = $('#addtothecart').data('id');
                var name = $('#addtothecart').find('h4').text();
                $.ajax({
                    async: true,
                    type: 'POST',
                    url: '/Cart/AddProToCart',
                    data: {
                        idtocart: id,
                        quantity: quantitydata
                    },
                    success: function () {
                        window.location.href = "/san-pham-con/"+name+"-" + id;

                    }, error: function () {


                    }

                });

            });


        });
    </script>
}

<div class="row" id="contentLarge">
    <div class="col-sm-12" id="ProductLarge12">
        <div class="col-sm-9 ">
            <div class="col-sm-7">
                <!--Detail Product-->
                <div id="proZoom">
                    <div class="slides-container" id="zoomimg">
                        <img />
                    </div>

                    <br>
                    <div class="smallProIcon">
                        @if (ViewBag.listimage != null)
                        {
                            foreach (var item in ViewBag.listimage)
                            {
                                <span class="slideitem">
                                    <img src="@item" />
                                </span>
                            }
                        }
                    </div>
                </div>

            </div>
            <div class="col-sm-5" id="ProLargecol5">
                <!--name product-->
                <div id="nameproduct">
                    <h4>@Model.Name</h4>
                </div>

                <div id="protocart">
                    <h3>@string.Format("{0:C}", Model.Price).Replace(",00", "")</h3>
                    <div class="onelinep"></div>

                    <div class="input-group input-group-lg quantityproduct">
                        <span class="input-group-btn">
                            <button class="btn btn-danger btn-number" data-type="minus" id="btnsub" type="button">
                                <span class="glyphicon glyphicon-minus" aria-hidden="true"></span>
                            </button>
                        </span>

                        <input id="datanumbercart" name="numberinput" type="text" class="form-control input-number"
                               value="1" min="1" max="100">

                        <span class="input-group-btn">
                            <button class="btn btn-danger btn-number" data-type="plus" id="btnadd" type="button">
                                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                            </button>
                        </span>
                    </div>
                    <!--Add to cart-->
                    <div id="addtothecart" data-id="@Model.ID"><h4 class="hide">@Model.MetaTitle</h4>
                        THÊM VÀO GIỎ
                    </div>
                </div>



            </div>


            <div class="col-sm-12">

                <!--Description-->
                <div id="detailDescription">
                    <!--<div id="detail1">MÔ TẢ</div>-->
                    <!--<div id="detail2">THÔNG SỐ KĨ THUẬT</div>-->
                    <ul>
                        <li id="detail1">MÔ TẢ</li>
                        <li id="detail2">
                            THÔNG SỐ KĨ THUẬT
                        </li>
                    </ul>
                </div>
                <!--Ajax-->
                <div id="contentDetailDes">
                    @{ Html.RenderAction("_DesDetailAjax", "DetailProduct",new { iddes = Model.ID });}
                </div>
                <div id="contentDetailConfig">
                    @{ Html.RenderAction("_ConfigDesAjax", "DetailProduct", new { idconfig = Model.ID });}
                </div>

            </div>
        </div>
        <div class="col-sm-3" id="ProductLarge2">
            <div class="itempopular">Mới Cập Nhật</div>
            <div class="ipopular">
                @foreach (var item in listnewpro)
                {
                    <span>
                        <img src="@item.Images" />
                        <a href="san-pham-con/@item.MetaTitle-@item.ID"><p>@item.Name</p></a>
                        <p>@string.Format("{0:C}", item.Price).Replace(",00", "")</p>
                    </span>
                }
            </div>
        </div>

    </div>
</div>

OnlineShop/Views/Product/ProductWithItem.cshtml
@model List<Model.EntityFramework.Product>

<!--Item Product-->
@section jsCus{
    
    }

@foreach (var item in Model)
{
    <div class="slide" data-id="@item.CategoryID">
        <div>
            <img src="@item.Images" />
        </div>
        <a href="/san-pham/@item.MetaTitle/@item.ID"><h4>@item.Name</h4></a>
        <h5>@string.Format("{0:C}", item.Price).Replace(",00", "")</h5>

        <a href="@Url.Action("AddProToCart", "Cart",new { idtocart = item.ID})" title="Thêm vào giỏ">
            <svg style="width:24px;height:24px" viewBox="0 0 24 24">
                <path fill="#282B3A"
                      d="M17,18A2,2 0 0,1 19,20A2,2 0 0,1 17,22C15.89,22 15,21.1 15,20C15,18.89 15.89,18 17,18M1,2H4.27L5.21,4H20A1,1 0 0,1 21,5C21,5.17 20.95,5.34 20.88,5.5L17.3,11.97C16.96,12.58 16.3,13 15.55,13H8.1L7.2,14.63L7.17,14.75A0.25,0.25 0 0,0 7.42,15H19V17H7C5.89,17 5,16.1 5,15C5,14.65 5.09,14.32 5.24,14.04L6.6,11.59L3,4H1V2M7,18A2,2 0 0,1 9,20A2,2 0 0,1 7,22C5.89,22 5,21.1 5,20C5,18.89 5.89,18 7,18M16,11L18.78,6H6.14L8.5,11H16Z" />
            </svg>
        </a>

    </div>
}